In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last"

import argparse
from ddpg_torch.ddpg_torch import Agent
import gym
import numpy as np
from lifting_rl.linkage_env import LinkageEnv

from livelossplot import PlotLosses

In [2]:
params = {
    "N_LINKS": 5,
    "PARAM_VALS": np.array([9.81], dtype=np.float32),
    "OBS_LOW": np.array([0.5, 1, -0.5, -2.5, -2], dtype=np.float32),
    "OBS_HIGH": np.array([2.5, 3.1, 2.2, -0.3, -0.2], dtype=np.float32),
    "SPEED_LIMIT": 8,
    "ACT_LIMIT": 100,
    "TIME_STEP": 0.01,
    "VIDEO_FPS": 30,
}


In [3]:
env = LinkageEnv(params, verbose=0)

observation_space:  Box(10,)
action_space:  Box(5,)


In [4]:
agent = Agent(
    lr_actor=0.000025,
    lr_critic=0.00025,
    input_dims=[25],
    tau=0.001,
    env=env,
    batch_size=64,
    layer1_size=400,
    layer2_size=300,
    n_actions=5,
    chkpt_dir = "/home/mans/Documents/ddpg"
    
)

In [6]:
agent.load_models()
for i in range(100000):
    done = False
    score = 0
    state = np.array([1.4993861662461676,1.6887208408893308,1.5188663851286528,-1.4618884620583108,
                      -1.2326123593367506, 0, 0, 0, 0, 0], dtype=np.float32)
    gpos = np.array([1.421502135073518,2.095432115039964,0.41198918993925143,-1.7801216549492886,-1.344960337484976], dtype=np.float32)
    obs = env.inference_reset(state, gpos)
    while not done:
        env.render()
        act = agent.inference_action(obs)
        new_state, reward, done, info = env.step(act)
        print(act)
        score += reward
        obs = new_state
env.close()

...loading checkpoint....
...loading checkpoint....
...loading checkpoint....
...loading checkpoint....
[-0.999946    0.99997056 -0.640591   -0.99996054  0.9928334 ]
[ 0.6437638  0.9999309 -0.5045007 -0.9993925  0.9624277]
[ 0.9999606   0.9999954  -0.5199798   0.8110078   0.91681087]
[ 0.9999839   0.999999   -0.8005068   0.99393743 -0.9004112 ]
[ 0.99999976  0.9999954  -0.74127334  0.99574256 -0.9992282 ]
[ 0.99999917  0.99969774  0.9560619   0.8439849  -0.96350163]
[-0.81442255  0.9637078   0.9997225  -0.9999938  -0.61626905]
[-0.21684028  0.3268452   0.9999882  -0.99999964 -0.853825  ]
[-0.99822026 -0.55834174  0.9999978  -1.         -0.9329122 ]
[-0.9999979  -0.98319703  0.9999992  -1.         -0.9972445 ]
[-1.         -0.99998647  0.9999955  -1.         -0.9998491 ]
[-1.        -0.9999997  0.9999863 -1.        -0.9994082]
[-1.         -1.          0.9999973  -1.         -0.99970925]
[-1.         -0.99999934  0.99989974 -1.         -0.9688675 ]
[-1.         -0.9999379   0.999772   -

[-0.9999794  -0.99955827  0.9998791   0.967241   -0.7666885 ]
[ 0.99999976  0.9565217   0.99857324 -0.9999996   0.98551035]
[-0.94622403 -0.99999994  0.99951535  0.647074   -0.79975545]
[ 0.9999999  -0.99981034  0.98654544 -0.99997234  0.70849437]
[-0.999252  -0.9995762  0.9999161  0.8553059 -0.6349818]
[ 0.99999994  0.90015155  0.999327   -0.9999994   0.97480804]
[-0.17195395 -0.99999994  0.9997266   0.7534301  -0.88334143]
[-0.95997715 -0.9999987   0.9945001  -0.99999285  0.76262313]
[ 1.         -0.9445003   0.99963343 -0.2897492  -0.6910726 ]
[-0.30350432 -0.45251307  0.9999567  -0.26104194  0.47093022]
[ 0.9989486  -0.81639206  0.99993205  0.94480175 -0.67348605]
[-1.         -0.85585034  0.9979569  -0.99967664  0.5509833 ]
[-0.9908833  0.9940631  0.9997672 -0.8615986 -0.9404135]
[ 1.         -0.9995256   0.99462956 -0.371654    0.13455822]
[ 0.99996054 -0.81621     0.99991256  0.9980145   0.9134738 ]
[-1.         -0.9750593   0.9996352   0.7598053  -0.80766565]
[-0.9987107  0.955

[ 1.         -0.99969125  0.8205026  -0.9999997   0.8988389 ]
[-0.9990405  -0.8408427   0.999493   -0.72478294 -0.9596753 ]
[ 1.          0.9649235   0.9933061  -0.998123   -0.00640783]
[-0.26645303 -0.99999994  0.99439573  0.99773383 -0.9212312 ]
[-0.8894516  -0.99999917  0.6326576  -0.99992996  0.92732525]
[-0.999946    0.99997056 -0.640591   -0.99996054  0.9928334 ]
[ 0.6437638  0.9999309 -0.5045007 -0.9993925  0.9624277]
[ 0.9999606   0.9999954  -0.5199798   0.8110078   0.91681087]
[ 0.9999839   0.999999   -0.8005068   0.99393743 -0.9004112 ]
[ 0.99999976  0.9999954  -0.74127334  0.99574256 -0.9992282 ]
[ 0.99999917  0.99969774  0.9560619   0.8439849  -0.96350163]
[-0.81442255  0.9637078   0.9997225  -0.9999938  -0.61626905]
[-0.21684028  0.3268452   0.9999882  -0.99999964 -0.853825  ]
[-0.99822026 -0.55834174  0.9999978  -1.         -0.9329122 ]
[-0.9999979  -0.98319703  0.9999992  -1.         -0.9972445 ]
[-1.         -0.99998647  0.9999955  -1.         -0.9998491 ]
[-1.        -

[-0.99999976 -0.9998015   0.99984777  0.97907746 -0.8071406 ]
[ 0.9999942   0.95700526  0.9964973  -0.99999946  0.9928435 ]
[-0.9998307  -1.          0.99920905  0.5631178  -0.79790395]
[ 0.99999946 -0.9998874   0.9630421  -0.9999627   0.87204176]
[-0.9999794  -0.99955827  0.9998791   0.967241   -0.7666885 ]
[ 0.99999976  0.9565217   0.99857324 -0.9999996   0.98551035]
[-0.94622403 -0.99999994  0.99951535  0.647074   -0.79975545]
[ 0.9999999  -0.99981034  0.98654544 -0.99997234  0.70849437]
[-0.999252  -0.9995762  0.9999161  0.8553059 -0.6349818]
[ 0.99999994  0.90015155  0.999327   -0.9999994   0.97480804]
[-0.17195395 -0.99999994  0.9997266   0.7534301  -0.88334143]
[-0.95997715 -0.9999987   0.9945001  -0.99999285  0.76262313]
[ 1.         -0.9445003   0.99963343 -0.2897492  -0.6910726 ]
[-0.30350432 -0.45251307  0.9999567  -0.26104194  0.47093022]
[ 0.9989486  -0.81639206  0.99993205  0.94480175 -0.67348605]
[-1.         -0.85585034  0.9979569  -0.99967664  0.5509833 ]
[-0.9908833  

KeyboardInterrupt: 